### PR TITLE
Add Option to disable the mow motor stop at obstacles

### PR DESCRIPTION
**Pull request by SirVival71**
There is a new define in config.h to disable the feature "stop the mow motor if obstacle detected". DISABLE_MOW_MOTOR_AT_OBSTACLE true // to stop the mow motor at detected obstacles (default in 1.0.298) DISABLE_MOW_MOTOR_AT_OBSTACLE false // Don't stop mow motor at detected obstacles (default in 1.0.230)

There is a second new define in config.h ENABLE_MOW_MOTOR to disable the mow motor permanently. For normal operation it is to be set to true.
It is useful to prevent mow motor activation at GPS testing, path tracking running test, perimeter. waypoint and exclusion changing tests, ... In these cases it is to be set to false.

Issue: There are users who are not enthused with the changed behavior 1.0230->1.0.298 that the mow motor stops at obstacles. There is one stop at detected obstacle. If it has not enough place to turn e.g. direct at the perimeter it will run in a second obstacle routine with a second mow motor stop, ... . It takes long time to restart the mow motor.
In case of used original brushless drivers of last year each mow motor stop is a risk of burned out brushless driver chip.

These defines are implemented that the default setting of true does not change the mower behavior of 1.0.298.

### CODE REVIEW

**Comment by Boilevin** [comment]
To understand the issue simply uncomment the console print  into motor.cpp and check the console
void Motor::setMowState(bool switchOn){
  //CONSOLE.print("Motor::setMowState ");
  //CONSOLE.println(switchOn);



So to avoid motor mow continue to stop :
line 343 to avoid motor stop 

 motor.setLinearAngularSpeed(linear, angular);      
    if (detectLift()) {
      mow = false; // in any case, turn off mower motor if lifted 
      motor.setMowState(mow);    
    }

**Comment by SirVival71** [comment]
The Issue is that the mow motor stops at detected obstacles. This would be fixed by this pull request.

see issue discussion in
https://forum.ardumower.de/threads/update-1-0-230-1-0-298-verhalten-obstacle_detection_rotation.25030/

**Comment by W1976** [comment]
@greymfm, bitte einfügen in die offizielle Firmware. Funktioniert gut bis jetzt und jeder kann selber entscheiden ob er mehr oder weniger Sicherheit möchte.

**Comment by SirVival71** [comment]
Conflict to Master 1.0.307 solved

**Comment by SirVival71** [comment]
Conflict to Master 1.0.309 solved

**Pull request merged**
