### PR TITLE
Update motor.cpp

### PR DESCRIPTION
**Pull request by fracii**
Unsure if added this code in the right place but going to test if it working

### CODE REVIEW

**Comment by greymfm** [comment]
Hello, Thanks for suggesting this patch - have you tested it already? :-)

**Comment by fracii** [comment]
> Hello, Thanks for suggesting this patch - have you tested it already? :-)

Hi @greymfm  I was going to try this now but I got some errors, I think I need to add declarations of all values in the code. Where do I add them? (Guessing motor.h?)


Here is error codes:

`Arduino:1.8.13 (Mac OS X), Kort:"Arduino Due (Native USB Port)"

motor.cpp:302:6: error: 'Robot' has not been declared
 void Robot::motorMowControl() {
      ^
sketch/motor.cpp: In function 'void motorMowControl()':
motor.cpp:304:18: error: 'nextTimeMotorMowControl' was not declared in this scope
   if (millis() < nextTimeMotorMowControl) return;
                  ^
motor.cpp:305:3: error: 'nextTimeMotorMowControl' was not declared in this scope
   nextTimeMotorMowControl = millis() + 100;
   ^
motor.cpp:306:7: error: 'motorMowForceOff' was not declared in this scope
   if (motorMowForceOff) motorMowEnable = false;
       ^
motor.cpp:306:25: error: 'motorMowEnable' was not declared in this scope
   if (motorMowForceOff) motorMowEnable = false;
                         ^
motor.cpp:310:7: error: 'motorMowEnable' was not declared in this scope
   if (motorMowEnable) {
       ^
motor.cpp:311:5: error: 'motorMowPowerMedian' was not declared in this scope
     motorMowPowerMedian.add(motorMowPower);
     ^
motor.cpp:311:29: error: 'motorMowPower' was not declared in this scope
     motorMowPowerMedian.add(motorMowPower);
                             ^
motor.cpp:313:24: error: 'motorMowPwmCoeff' was not declared in this scope
       int prevcoeff =  motorMowPwmCoeff;
                        ^
motor.cpp:314:81: error: 'motorMowPowerMax' was not declared in this scope
       motorMowPwmCoeff = int((100 * motorMowPowerMedian.getAverage(4)) / (0.5 * motorMowPowerMax));
                                                                                 ^
motor.cpp:319:12: error: 'statusCurr' was not declared in this scope
       if ((statusCurr == WIRE_MOWING) || (statusCurr == SPIRALE_MOWING)) motorMowPwmCoeff = 100;
            ^
motor.cpp:319:26: error: 'WIRE_MOWING' was not declared in this scope
       if ((statusCurr == WIRE_MOWING) || (statusCurr == SPIRALE_MOWING)) motorMowPwmCoeff = 100;
                          ^
motor.cpp:319:57: error: 'SPIRALE_MOWING' was not declared in this scope
       if ((statusCurr == WIRE_MOWING) || (statusCurr == SPIRALE_MOWING)) motorMowPwmCoeff = 100;
                                                         ^
motor.cpp:322:9: error: 'motorMowSpeedPWMSet' was not declared in this scope
         motorMowSpeedPWMSet = motorMowSpeedMinPwm + ((double)(motorMowSpeedMaxPwm - motorMowSpeedMinPwm)) * (((double)motorMowPwmCoeff) / 100.0);
         ^
motor.cpp:322:31: error: 'motorMowSpeedMinPwm' was not declared in this scope
         motorMowSpeedPWMSet = motorMowSpeedMinPwm + ((double)(motorMowSpeedMaxPwm - motorMowSpeedMinPwm)) * (((double)motorMowPwmCoeff) / 100.0);
                               ^
motor.cpp:322:63: error: 'motorMowSpeedMaxPwm' was not declared in this scope
         motorMowSpeedPWMSet = motorMowSpeedMinPwm + ((double)(motorMowSpeedMaxPwm - motorMowSpeedMinPwm)) * (((double)motorMowPwmCoeff) / 100.0);
                                                               ^
motor.cpp:324:11: error: 'motorMowSpeedPWMSet' was not declared in this scope
       if (motorMowSpeedPWMSet < motorMowSpeedMinPwm) motorMowSpeedPWMSet = motorMowSpeedMinPwm;
           ^
motor.cpp:324:33: error: 'motorMowSpeedMinPwm' was not declared in this scope
       if (motorMowSpeedPWMSet < motorMowSpeedMinPwm) motorMowSpeedPWMSet = motorMowSpeedMinPwm;
                                 ^
motor.cpp:325:11: error: 'motorMowSpeedPWMSet' was not declared in this scope
       if (motorMowSpeedPWMSet > motorMowSpeedMaxPwm) motorMowSpeedPWMSet = motorMowSpeedMaxPwm;
           ^
motor.cpp:325:33: error: 'motorMowSpeedMaxPwm' was not declared in this scope
       if (motorMowSpeedPWMSet > motorMowSpeedMaxPwm) motorMowSpeedPWMSet = motorMowSpeedMaxPwm;
                                 ^
motor.cpp:332:5: error: 'motorMowSpeedPWMSet' was not declared in this scope
     motorMowSpeedPWMSet = 0;
     ^
motor.cpp:334:7: error: 'stateCurr' was not declared in this scope
   if (stateCurr == STATE_ERROR) {
       ^
motor.cpp:334:20: error: 'STATE_ERROR' was not declared in this scope
   if (stateCurr == STATE_ERROR) {
                    ^
motor.cpp:335:28: error: 'setMotorMowPWM' was not declared in this scope
     setMotorMowPWM(0, false); //stop immediatly on error (tilt etc....)
                            ^
motor.cpp:339:20: error: 'motorMowSpeedPWMSet' was not declared in this scope
     setMotorMowPWM(motorMowSpeedPWMSet, true);
                    ^
motor.cpp:339:45: error: 'setMotorMowPWM' was not declared in this scope
     setMotorMowPWM(motorMowSpeedPWMSet, true);
                                             ^
exit status 1
'Robot' has not been declared


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by felixganzer** [comment]
At first you schould change the class of your function from Robot to Motor that will reduce your errors. If you use variables as local variables add the declatation at the function alle other schould be declared at motor.h

A different proposal could be the following: with every loop reduce the speed of the mower for example 5% if the current of the mowMotor is higher than 50 %. If the current is higher rise the mowMotor speed up to maximum. 

This classical rule loop is very simple to impement, because it is a simple if condition.

void Motor::begin() {
  pwmMax = 255;
  pwmMaxMow = 190;
  pwmSpeedOffset = 1.0;
  pwmSpeedOffsetTick = 0.05;
  .......
}

void Motor::speedPWM ( int pwmLeft, int pwmRight, int pwmMow )
{
  pwmLeft = min(pwmMax, max(-pwmMax, pwmLeft));
  pwmRight = min(pwmMax, max(-pwmMax, pwmRight));  
  pwmMow = min(pwmMaxMow, max(-pwmMaxMow, pwmMow));  
    
  if (motorLeftSwapDir) pwmLeft *= -1;
  if (motorRightSwapDir) pwmRight *= -1;

  if (pwmMow != 0)
  {
    if (motorMowSenseLP > 0.5 * MOW_OVERLOAD_CURRENT) pwmSpeedOffset -= pwmSpeedOffsetTick;
    if (motorMowSenseLP < 0.5 * MOW_OVERLOAD_CURRENT) pwmSpeedOffset += pwmSpeedOffsetTick;

    pwmLeft  = (int)(pwmLeft * pwmSpeedOffset);
    pwmRight = (int)(pwmRight * pwmSpeedOffset);
  }
  
  motorDriver.setMotorPwm(pwmLeft, pwmRight, pwmMow);
}

**Comment by stephwe** [comment]
Kommt folgender Code auch in die motor.ccp oder eher in die motor.h

`pwmLeft  = (int)(pwmLeft * pwmSpeedOffset);

pwmRight = (int)(pwmRight * pwmSpeedOffset);`

Beim kompilieren bekomme ich den Fehler das pwmSpeedOffset nicht deklariert ist.

**Comment by felixganzer** [comment]
Die variable pwmSpeedOffset ist an der stelle nicht declariert. Diese kann an dieser stelle lokal in dieser funktion deklarieren. Ich muss dir davon abraten diesen Codeschnipsel zu verwenden. Dieser ist nur ein fragment und es fehlen viele Fehlerabfragen und Begrenzungen. 

Ich bin gerade dabei das richtig zu programmieren und zu testen. In ca. 2 Wochen werde ich den fertigen Code commiten. Dieser beeinhaltet dann eine dynamische Anpassung der Fahrgeschwindigkeit und des Mähmotors.

**Comment by felixganzer** [comment]
Ich habe mal ein pull request mit meinem Code gemacht. Dieser ist von mir getestet und im Betrieb.

**Comment by stephwe** [comment]
Today I have the tested code.
Basically everything works. There were the following problems:
At "#define DYNAMIC_MOWMOTOR_ALGORITHM 1" the mower motor pulsed
With "#define DYNAMIC_MOWMOTOR_ALGORITHM 2" the speed reduction
works, but has not reset over time,
i.e. the mover remained slow, even though it had driven over a long paved path and the load according to the app was only 0.5A.
The general feeling is that the motor control reacts very sensitively, the grass was not very high today and the last one was actually always below 1A according to the app. In theory, the dynamic engine management system would not have had any reason to intervene.
What do the functions "linear, root & square" mean?
From what load of the mower motor can the motor control for the mower motor and motion motors intervene?

**Comment by felixganzer** [comment]
Linear, root und square sind die funktionen, mit welcher Y (PWM Mähmotor) von X (Current Mähmotor) abhängig ist. Die Wurzelfunktion (root) sollte die besten Ergebnisse liefern. Diese nutze ich und habe diese auch nur verwendet. Die anderen habe ich nur der Vollständigkeit integriert. 

Die Fahrgeschwindigkeit ist eine andere Sache. Ich habe 2 Sachen gemacht. Wenn du #define USE_MOWMOTOR_CURRENT_AVERAGE auf false setzt, kannst du einen festen Faktor auf den MOW_OVERLOAD_CURRENT angeben.

Wenn man #define USE_MOWMOTOR_CURRENT_AVERAGE auf true setzt, macht der Algorithmus folgendes: Wenn die PWM des Mähmotors im der Nähe des Mittelwertes zwischen PWM_Min und PWM_Max ist, wird geschaut, wie hoch der Strom am Mähmotor ist. Aus diesen Werten wird ein gleitender Durschnitt über 10000 Punkte gebildet. Dieser ist dann der Referenzwert für den Schwellwert der Geschwindigkeitssteuerung.

Ich hoffe das war verständlich.

Im Code sind noch ein paar Faktoren, welche anscheinend noch nicht optimal sind. Dies benötigt relativ viel Zeit zum testen.

Als Vorschlag: setze mal den #define USE_MOWMOTOR_CURRENT_AVERAGE auf false.

Ich habe das nur schonmal commited, weil ich überhaupt nicht einschätzen kann, ob mein Code überhaupt akzeptiert wird.

**Comment by stephwe** [comment]
na klar wird dein Code akzeptiert. Das ist ein wunderbare Erweiterung, alle Daumen hoch und Hut ab.
Wenn ich #define USE_MOWMOTOR_CURRENT_AVERAGE auf false setze wird vom maximalen MOW_OVERLOAD_CURRENT ausgegangen und dementsprechend geregelt? Setzt die Regelung erst ein wenn MOW_OVERLOAD_CURRENT überschritten wird oder wird auch schon vorher geregelt?

**Comment by felixganzer** [comment]
Es wird von anfang an geregelt. Ich brauchte nur einen Fixpunkt für den Schwellwert. Da habe ich mich für diesen Wert entschieden. Ich habe an der Stelle einmal den Standardwert von 2 Ampere stehen und dann den Faktor 0.25. Daraus ergibt sich 0.5 Ampere als Schwellwert. Es wird aktuell gebremst, wenn kleiner 0.9 * Schwellwert und beschleunigt, wenn 1.1 * Schwellwert. Ich halte eine Hysterese an dieser Stelle für sinnvoll. 

Die Beschleunigung kannst du auch anpassen.

**Comment by stephwe** [comment]
Ich habe den Mover jetzt noch das 2.Mal rausgejagt und den Wert  #define USE_MOWMOTOR_CURRENT_AVERAGE auf false gesetzt. 
#define DYNAMIC_MOWMOTOR_ALGORITHM " habe ich wieder auf 2 (root) gesetzt, ansonsten keine Werte verändert.
Es gab jetzt keine sichtbaren Eingriffe mehr. Die Werte im seriellen Monitor haben sich auch nicht groß verändert.
Da der Rasen ja schon gemäht ist und kein hohes Gras mehr da ist gehe ich mal von aus das so alles richtig ist.  
Ich werde jetzt mal ein paar Tage warten bis der Rasen nachgewachsen ist und dann teste ich weiter.
Super Sache auf jeden Fall!

**Comment by stephwe** [comment]
Hallo Felix, noch mal ganz kurz 2 Verständnisfragen:
Wenn ich #define USE_MOWMOTOR_CURRENT_AVERAGE auf false setze wird trotzdem die Fahrgeschwindigkeit geregelt?
Wenn #define USE_MOWMOTOR_CURRENT_AVERAGE auf false gesetzt ist dann steht der Wert, der für die Regelung maßgebend ist unter MOW_OVERLOAD_CURRENT? Setze ich also diesen Wert von z.B. 2.0 auf 1,5 runter wird früher die Geschwindigkeit gedrosselt und die Mähmotorleistung erhöht?
Vielen Dank und Sorry

**Comment by felixganzer** [comment]
Erste Frage: Ja.
Zweite Frage: Du setzt den Wert MOWMOTOR_CURRENT_FACTOR. Dieser Faktor bezieht sich auf den MOW_OVERLOAD_CURRENT. 

Der erste Wert ist bei mir 0.25, der zweite Wert ist 2.0 Ampere. Das ergibt als Schwellwert für die Regelung 0.5 Ampere

Ich glaube ich sollte eine ausführliche Anleitung schreiben :D

**Comment by stephwe** [comment]
Hallo Felix,
vielen Dank. Jetzt habe ich es verstanden und heute ausgiebig getestet. 
#define USE_MOWMOTOR_CURRENT_AVERAGE ist auf false gesetzt, ansonsten alles Standardwerte.
Ich konnte heute gut sehen wie er die Geschwindigkeit den Rasenverhältnissen angepasst hat. Hat alles super funktioniert, keine Aussetzer oder merkwürdiges Verhalten.
Die Regelung des Messermotors konnte ich nur im Monitor verfolgen, hat aber auch sehr gut funktioniert.

**Comment by greymfm** [comment]
closed as feature is already included in another pull request (https://github.com/Ardumower/Sunray/pull/24)

**Pull request closed without merging**
