### PR TITLE
Fix MQTT communication

### PR DESCRIPTION
**Pull request by EinEinfach**
1. Bug fix MQTT comunication.
- MQTT topics state, props and subscription command/start, command/stop and command/dock are available aqain
2. Added new topic stats
- Statistic data is also available on MQTT
3. Added new subscriptions
- Reboot the robot by command/reboot
- Switch off the robot by command/shutdown

### CODE REVIEW

**Comment by greymfm** [comment]
Thank you!

**Comment by disaster123** [comment]
Is there any reason there is currently no user / pass authentication?

**Comment by EinEinfach** [comment]
> Is there any reason there is currently no user / pass authentication?

Nope, actually not. The main goal was to fix the legacy code from timotto without any untested changes

**Comment by disaster123** [comment]
OK thanks implemented here: https://github.com/Ardumower/Sunray/pull/93

**Comment by EinEinfach** [comment]
> OK thanks implemented here: #93

Sorry but this changes affect MQTT Communication handle by ESP32 not by Sunray Code. Why it wasn‘t in Sunray, I don‘t know. Anyway seems to be already merged

**Pull request merged**
